version: '3'

services:
  sc-es01:
    container_name: sc-es01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    # image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2
    restart: always
    volumes:
      - //C/Users/huongnv/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - //C/Users/huongnv/elk/es01/data:/usr/share/elasticsearch/data
      # - //C/Users/huongnv/elk/es01/logs/:/usr/share/elasticsearch/logs
    environment:
      - node.name=sc-es01
      - discovery.seed_hosts=sc-es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300

  sc-es02:
    container_name: sc-es02
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    # image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2
    restart: always
    volumes:
      - //C/Users/huongnv/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - //C/Users/huongnv/elk/es02/data:/usr/share/elasticsearch/data
      # - //C/Users/huongnv/elk/es02/logs/:/usr/share/elasticsearch/logs
    environment:
      - node.name=sc-es02
      - discovery.seed_hosts=sc-es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  sc-logstash:
    container_name: sc-logstash
    image: nhdocker/logstash:7.4.2
    # image: docker.elastic.co/logstash/logstash-oss:7.4.2
    build:
      context: ./logstash
      dockerfile: Dockerfile
    restart: always
    volumes:
      # - //C/Users/huongnv/elk/logstash/pipeline:/usr/share/logstash/pipeline
      - //C/Users/huongnv/elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - //C/Users/huongnv/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - //C/Users/huongnv/elk/logstash/conf.d:/etc/logstash/conf.d
      - //C/Users/huongnv/elk/tls/certs:/etc/pki/tls/certs
      - //C/Users/huongnv/elk/logstash/logs:/var/log/logs
      - //C/Users/huongnv/elk/nginx/logs:/var/log/nginx
    depends_on:
      - sc-es01
      - sc-es02
      # - sc-redis
    ports:
      - 5044:5044

  sc-kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    # image: docker.elastic.co/kibana/kibana-oss:7.4.2
    container_name: sc-kibana
    volumes:
      - //C/Users/huongnv/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - sc-es01
      - sc-es02
    ports:
      - 5601:5601

  # sc-redis:
  #   image: redis
  #   container_name: sc-redis
  #   restart: always
  #   command: redis-server --appendonly yes --requirepass redis080
  #   volumes:
  #     - //C/Users/huongnv/elk/redis/data:/data
  #   ports:
  #     - 6379:6379

  # sc-redis-ui:
  #   image: rediscommander/redis-commander
  #   container_name: sc-redis-ui
  #   restart: always
  #   environment:
  #     REDIS_HOSTS: 'local:sc-redis:6379:0:redis080'
  #     # REDIS_PASSWORD: redis080
  #     TZ: 'Asia/Tokyo'
  #   depends_on:
  #     - sc-redis
  #   ports:
  #     - 7081:8081

  sc-nginx:
    image: nginx:latest
    container_name: sc-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - //C/Users/huongnv/elk/nginx/logs:/var/log/nginx
